============================= test session starts ==============================
platform linux2 -- Python 3.2.2 -- pytest-2.2.3
collecting ... collected 4 items

prime_factor.py .FFF

=================================== FAILURES ===================================
________________________________ test_primes_2 _________________________________

    def test_primes_2():
>       assert primes(2) == [2]
E       assert None == [2]
E        +  where None = primes(2)

prime_factor.py:24: AssertionError
------------------------------- Captured stdout --------------------------------
** test 2
new nb is 1
** test 1
[]
________________________________ test_primes_3 _________________________________

    def test_primes_3():
>       assert primes(3) == [3]
E       assert None == [3]
E        +  where None = primes(3)

prime_factor.py:27: AssertionError
------------------------------- Captured stdout --------------------------------
** test 3
new nb is 1
** test 1
[]
________________________________ test_primes_4 _________________________________

    def test_primes_4():
>       assert primes(4) == [2, 2]
E       assert None == [2, 2]
E        +  where None = primes(4)

prime_factor.py:30: AssertionError
------------------------------- Captured stdout --------------------------------
** test 4
new nb is 2
** test 2
new nb is 1
** test 1
[]
None
new nb is 1
** test 1
[]
====================== 3 failed, 1 passed in 0.04 seconds ======================
