============================= test session starts ==============================
platform linux2 -- Python 3.2.2 -- pytest-2.2.3
collecting ... collected 4 items

prime_factor.py FFFF

=================================== FAILURES ===================================
________________________________ test_primes_1 _________________________________

    def test_primes_1():
>       assert primes(1) == []
E       assert None == []
E        +  where None = primes(1)

prime_factor.py:18: AssertionError
------------------------------- Captured stdout --------------------------------
** test 1
________________________________ test_primes_2 _________________________________

    def test_primes_2():
>       assert primes(2) == [2]
E       assert None == [2]
E        +  where None = primes(2)

prime_factor.py:21: AssertionError
------------------------------- Captured stdout --------------------------------
** test 2
** test 1
None
________________________________ test_primes_3 _________________________________

    def test_primes_3():
>       assert primes(3) == [3]
E       assert None == [3]
E        +  where None = primes(3)

prime_factor.py:24: AssertionError
------------------------------- Captured stdout --------------------------------
** test 3
** test 1
None
________________________________ test_primes_4 _________________________________

    def test_primes_4():
>       assert primes(4) == [2, 2]
E       assert None == [2, 2]
E        +  where None = primes(4)

prime_factor.py:27: AssertionError
------------------------------- Captured stdout --------------------------------
** test 4
** test 2
** test 1
None
None
** test 1
None
=========================== 4 failed in 0.04 seconds ===========================
