============================= test session starts ==============================
platform linux2 -- Python 3.2.2 -- pytest-2.2.3
collecting ... collected 4 items

prime_factor.py FFFF

=================================== FAILURES ===================================
________________________________ test_primes_1 _________________________________

    def test_primes_1():
>       assert primes(1) == []
E       assert None == []
E        +  where None = primes(1)

prime_factor.py:17: AssertionError
________________________________ test_primes_2 _________________________________

    def test_primes_2():
>       assert primes(2) == [2]
E       assert None == [2]
E        +  where None = primes(2)

prime_factor.py:20: AssertionError
------------------------------- Captured stdout --------------------------------
None
________________________________ test_primes_3 _________________________________

    def test_primes_3():
>       assert primes(3) == [3]
E       assert None == [3]
E        +  where None = primes(3)

prime_factor.py:23: AssertionError
------------------------------- Captured stdout --------------------------------
None
________________________________ test_primes_4 _________________________________

    def test_primes_4():
>       assert primes(4) == [2, 2]
E       assert None == [2, 2]
E        +  where None = primes(4)

prime_factor.py:26: AssertionError
------------------------------- Captured stdout --------------------------------
None
None
None
=========================== 4 failed in 0.04 seconds ===========================
